Vagrant.configure("2") do |config|
  config.vm.box = "parallels/ubuntu-16.04"
  config.vm.network "private_network", ip: "192.168.100.5"
  config.vm.provider "parallels" do |prl|
    prl.name = "alpha"
    prl.linked_clone = true
    prl.update_guest_tools = true
    prl.memory = 4096
    prl.cpus = 2
  end
end
