alias l="LC_COLLATE=C ls -Alhp --color=auto --group-directories-first"
alias ll="l"
alias b="cd .."
alias c="clear"
alias down="cd ~/Downloads"
alias mongos="docker run --name viper -d -p 27017:27017 -v /home/chyld/Data/mongo:/data/db mongo"
alias mongoc="docker run -it --link viper:mongo --rm mongo sh -c 'exec mongo "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/test"'"
