import = ["/home/chyld/.config/alacritty/themes/themes/everforest_dark.toml"]

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

#[window.dimensions]
#columns = 120
#lines = 25

