alias l="ls -pahlGF"
alias ll="l"
alias g="git"
alias b="cd .."
alias c="clear"
alias d="docker"
alias down="cd ~/Downloads"
alias docs="cd ~/Documents"
alias desk="cd ~/Desktop"
alias data="cd ~/Data"
alias hack="cd ~/Code"
alias temp="cd ~/Temp"
alias dc="docker-compose"
alias reload="source ~/.bash_profile"
alias mongodb="docker run --name viper -d -p 27017:27017 -v /Users/chyld/Data/mongo:/data/db mongo"
alias mysqldb="docker run --name titan -d -e MYSQL_ROOT_PASSWORD=pass1234 -p 3306:3306 -v /Users/chyld/Data/mysql/data:/var/lib/mysql -v /Users/chyld/Data/mysql/logs:/var/log/mysql mysql"
