alias l='exa -lFa --git'
alias ll='exa -lFaT --git --level=3'
alias lll='exa -lFaT --git --level=5'
alias h='history'
alias c='clear'
alias b='cd ..'
alias d='docker'
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias n='open_nautilus'
alias cat='bat'
alias myip='http -b ipinfo.io/ip'
alias jj1="jupyter console"
alias jj2='jupyter qtconsole --style monokai &'
alias jj3="jupyter notebook"
