#!/bin/bash

port=$1

if [ -z "$port" ]; then
  port=3333
fi

# i am removing "--rm" so that i can have the option of
# keeping the container if i want it later

docker run -it -p "$port":"$port"   \
  -v /Users/chyld:/home/chyld/macOS      \
  -v ephemeral:/home/chyld/X             \
  prometheus:latest

# # #
# #
#
