#!/bin/bash

# view log at /var/log/syslog
# it is executed as the logged in user
# the current working directory is the folder you are in currently

zenity --question --text="Are you sure you want to permanently delete the selected file(s)?" --title="Confirm Delete" --no-wrap
if [ $? -ne 0 ]; then
    logger -t "chyld-delete" "Deletion cancelled by user"
    exit 0
fi

IFS=$'\n'
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
  logger -t "chyld-delete" "$file was deleted"
  rm -rf "$file"
done
