#!/bin/bash

# ------------------------------------------------------------------------------
# usage: dev <port> <name>
#
# ------------------------------------------------------------------------------

port=$1
name=$2

if [ -z "$port" ]; then
  echo "no port"
  exit 1
fi

if [ -z "$name" ]; then
  echo "no name"
  exit 1
fi

does_port_exist=$(docker ps -a --format '{{ .Ports }}' | grep -i "$port")

if [ -n "$does_port_exist" ]; then
  echo "port $port already in use"
  exit 1
fi

# ./dev 3333 alpha
# if you do not use "-it" then the container will stop
# else if you do use "-it" then the container will continue to run

docker run -p "$port":"$port"            \
  --name "$name"                         \
  -v /Users/chyld:/home/chyld/macOS      \
  -v ephemeral:/home/chyld/X             \
  -it                                    \
  -d                                     \
  prometheus:latest

# # #
# #
#

