alias l="ls -pahlGF"
alias ll="l"
alias g="git"
alias b="cd .."
alias c="clear"
alias d="docker"
alias down="cd ~/Downloads"
alias dc="docker-compose"
alias reload="source ~/.bash_profile"
alias mongodb="docker run --name viper -d -p 27017:27017 -v /Users/chyld/Data/mongo:/data/db mongo"
alias mysqldb="docker run --name titan -d -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 -v /Users/chyld/Data/mysql:/var/lib/mysql mysql"
